### ISSUE TITLE
Not able to convert my JS to TS throws error

### ISSUE THREAD

**Issue by vijthang61** [gregjacobs/js-to-ts-converter#2]
info:   Adding property declarations to JS Classes...
verbose:        Parsing JS classes in the codebase...
verbose:          Updating class 'OuiTable' in 'D:/dis/ui/src/main/webapp/src/js/app/modules/common/table/ouiTable.js'
verbose:            Adding property declarations for properties: 'state', 'setState', 'props', 'lastQuery', 'pageSize', 'currentPage', 'sorting', 'searchStr', 'rows', 'prepareData', 'selection', 'intl', 'id', 'sort', 'pagination', 'rowActions', 'search', 'tableActions'
verbose:          Updating class 'Pagination' in 'D:/dis/ui/src/main/webapp/src/js/app/modules/common/table/pagination.js'
verbose:            Adding property declarations for properties: 'props', 'count', 'onChangePage', 'page', 'rowsPerPage', 'ActionsComponent', 'backIconButtonProps', 'classes', 'Component', 'labelDisplayedRows', 'labelRowsPerPage', 'nextIconButtonProps', 'onChangeRowsPerPage', 'rowsPerPageOptions', 'SelectProps'
verbose:          Updating class 'paginationActions' in 'D:/dis/ui/src/main/webapp/src/js/app/modules/common/table/paginationActions.js'
verbose:            Adding property declarations for properties: 'props', 'classes', 'count', 'page', 'rowsPerPage', 'theme'
verbose:          Updating class 'Table' in 'D:/dis/ui/src/main/webapp/src/js/app/modules/common/table/table.js'
verbose:            Adding property declarations for properties: 'state', 'columns', 'props', 'setState', 'lastQuery', 'pageSize', 'currentPage', 'sorting', 'intl'
verbose:          Updating class 'TableHeader' in 'D:/dis/ui/src/main/webapp/src/js/app/modules/common/table/tableHeader.js'
verbose:            Adding property declarations for properties: 'props'
info:   Renaming .js files to .ts
C:\Users\vijthang.ORADEV\AppData\Roaming\npm\node_modules\js-to-ts-converter\node_modules\ts-simple-ast\dist\manipulation\nodeHandlers\StraightReplacementNodeHandler.js:34
            finally { if (e_1) throw e_1.error; }
                               ^

Error: Error replacing tree: Should not have new children left over.
    at StraightReplacementNodeHandler.handleNode (C:\Users\vijthang.ORADEV\AppData\Roaming\npm\node_modules\js-to-ts-converter\node_modules\ts-simple-ast\dist\manipulation\nodeHandlers\StraightReplacementNodeHandler.js:38:19)
    at NodeHandlerHelper.handleForValues (C:\Users\vijthang.ORADEV\AppData\Roaming\npm\node_modules\js-to-ts-converter\node_modules\ts-simple-ast\dist\manipulation\nodeHandlers\NodeHandlerHelper.js:10:21)
    at StraightReplacementNodeHandler.handleNode (C:\Users\vijthang.ORADEV\AppData\Roaming\npm\node_modules\js-to-ts-converter\node_modules\ts-simple-ast\dist\manipulation\nodeHandlers\StraightReplacementNodeHandler.js:26:29)
    at NodeHandlerHelper.handleForValues (C:\Users\vijthang.ORADEV\AppData\Roaming\npm\node_modules\js-to-ts-converter\node_modules\ts-simple-ast\dist\manipulation\nodeHandlers\NodeHandlerHelper.js:10:21)
    at StraightReplacementNodeHandler.handleNode (C:\Users\vijthang.ORADEV\AppData\Roaming\npm\node_modules\js-to-ts-converter\node_modules\ts-simple-ast\dist\manipulation\nodeHandlers\StraightReplacementNodeHandler.js:26:29)
    at NodeHandlerHelper.handleForValues (C:\Users\vijthang.ORADEV\AppData\Roaming\npm\node_modules\js-to-ts-converter\node_modules\ts-simple-ast\dist\manipulation\nodeHandlers\NodeHandlerHelper.js:10:21)
    at StraightReplacementNodeHandler.handleNode (C:\Users\vijthang.ORADEV\AppData\Roaming\npm\node_modules\js-to-ts-converter\node_modules\ts-simple-ast\dist\manipulation\nodeHandlers\StraightReplacementNodeHandler.js:26:29)
    at NodeHandlerHelper.handleForValues (C:\Users\vijthang.ORADEV\AppData\Roaming\npm\node_modules\js-to-ts-converter\node_modules\ts-simple-ast\dist\manipulation\nodeHandlers\NodeHandlerHelper.js:10:21)
    at StraightReplacementNodeHandler.handleNode (C:\Users\vijthang.ORADEV\AppData\Roaming\npm\node_modules\js-to-ts-converter\node_modules\ts-simple-ast\dist\manipulation\nodeHandlers\StraightReplacementNodeHandler.js:26:29)
    at NodeHandlerHelper.handleForValues (C:\Users\vijthang.ORADEV\AppData\Roaming\npm\node_modules\js-to-ts-
converter\node_modules\ts-simple-ast\dist\manipulation\nodeHandlers\NodeHandlerHelper.js:10:21)

Sample file
[tableHeader.zip](https://github.com/gregjacobs/js-to-ts-converter/files/3057465/tableHeader.zip)

**Comment by vijthang61** [comment]
> Hey, thanks for the report, and sending the code file! I'll try to take a look when I get home tonight
> 
> Best,
> Greg

Any  updates on this

**Comment by vijthang61** [comment]
I am still waiting on this, can you let me know, when this can be fixed.

**Comment by gregjacobs** [comment]
Hey @vijthang61, I'm so sorry. We had a family emergency and I haven't had a chance to look at it :( 

Thanks for letting me know you're still looking for the fix though. Let me see what I can do.

**Comment by gregjacobs** [comment]
Hey @vijthang61, I'm just realizing that you're converting a React codebase to TypeScript. In that case, you might want to use this project: https://github.com/lyft/react-javascript-to-typescript-transform. This looks like it will do a lot more for your React codebase than my utility (although I will try to fix your error anyway as that shouldn't happen :))

**Comment by gregjacobs** [comment]
Hey @vijthang61. I was able to fix this in v0.16.3, but def recommend checking out that other project since it looks like it's going to do a lot more for you in terms of React. Let me know how it goes!

Best,
Greg
