### ISSUE TITLE
Stack: RangeError: Maximum call stack size exceede

### ISSUE THREAD

**Issue by shalaga44** [gregjacobs/js-to-ts-converter#21]
Try an **Iterative Solution**
```
`/usr/local/lib/node_modules/js-to-ts-converter/node_modules/ts-morph/dist/ts-morph.js:2274
            throw new ManipulationError(sourceFile.getFilePath(), oldFileText, newFileText, message);
            ^

Error: Manipulation error: Maximum call stack size exceeded

-- Details --
Path: /home/shalaga44/WebstormProjects/telehealth/src/ts/matx/components/Breadcrumb.tsx
Text: "import React from \"react\";\nimport { Icon, Breadcrumbs, Hidden } from \"@material-ui/core\";\nimport { NavLink } from \"react-router-dom\";\n\nconst Breadcrumb = ({ routeSegments }) => {\n  return (\n    <div className=\"flex flex-wrap items-center\">\n      {routeSegments ? (\n        <Hidden xsDown>\n          <h4 className=\"m-0 pb-1px text-16 capitalize align-middle\">\n            {routeSegments[routeSegments.length - 1][\"name\"]}\n          </h4>\n          <h4 className=\"m-0 pb-3px ml-2 text-hint\">|</h4>\n        </Hidden>\n      ) : null}\n      <Breadcrumbs\n        separator={<Icon className=\"text-hint\">navigate_next</Icon>}\n        className=\"flex items-center position-relative\"\n      >\n        <NavLink to=\"/\">\n          <Icon className=\"align-middle ml-2 mb-1\" color=\"primary\">\n            home\n          </Icon>\n        </NavLink>\n        {routeSegments\n          ? routeSegments.map((route, index) => {\n              return index !== routeSegments.length - 1 ? (\n                <NavLink key={index} to={route.path}>\n                  <span className=\"capitalize text-muted\">{route.name}</span>\n                </NavLink>\n              ) : (\n                <span key={index} className=\"capitalize text-muted\">\n                  {route.name}\n                </span>\n              );\n            })\n          : null}\n      </Breadcrumbs>\n    </div>\n  );\n};\n\nexport default Breadcrumb;\n"
Stack: RangeError: Maximum call stack size exceeded
    at visitNodes (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:27033:24)
    at forEachChild (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:27275:24)
    at gatherPossibleChildren (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:27547:13)
    at Object.forEachChildRecursively (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:27539:56)
    at Object.setParentRecursive (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:19052:12)
    at fixupParentReferences (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:28082:16)
    at parseSourceFileWorker (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:27961:17)
    at Object.parseSourceFile (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:27798:26)
    at Object.createSourceFile (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:27598:29)
    at Object.createLanguageServiceSourceFile (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:143700:29)
    at throwError (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/ts-morph/dist/ts-morph.js:2274:19)
    at doManipulation (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/ts-morph/dist/ts-morph.js:2272:9)
    at replaceSourceFileForFilePathMove (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/ts-morph/dist/ts-morph.js:2701:5)
    at SourceFile._moveInternal (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/ts-morph/dist/ts-morph.js:12682:9)
    at SourceFile.move (/usr/local/lib/node_modules/js-to-ts-converter/node_modules/ts-morph/dist/ts-morph.js:12658:19)
    at tsAstProject.getSourceFiles.forEach.sourceFile (/usr/local/lib/node_modules/js-to-ts-converter/dist/converter/convert.js:44:24)
    at Array.forEach (<anonymous>)
    at Object.convert (/usr/local/lib/node_modules/js-to-ts-converter/dist/converter/convert.js:33:35)
    at doConvert (/usr/local/lib/node_modules/js-to-ts-converter/dist/js-to-ts-converter.js:85:22)
    at Object.convertJsToTsSync (/usr/local/lib/node_modules/js-to-ts-converter/dist/js-to-ts-converter.js:63:35)`
```

**Comment by gregjacobs** [comment]
How about **you** try an iterative solution @shalaga44? PRs welcome!

**Comment by milkcoke** [comment]
I also got this error too.. @shalaga44 . 
Is there any other solution?
target .js files were just 500 lines..

**Comment by gregjacobs** [comment]
Hey @milkcoke, can you point me to your repository so I can try the utility against it and debug?

**Comment by JDMathew** [comment]
Also having this issue

**Comment by codascii** [comment]
Is someone found a solution for that ? I have the same error.

**Comment by JDMathew** [comment]
I had to unfortunately make the changes manually. It seemed certain files caused it to get into an infinite loop which exceeded the call stack. Even files with relatively few lines. I was unable to pin down the issue but noticed it happened a lot more on files which had gql documents in them.

**Comment by gregjacobs** [comment]
Sadly without any code or repository to reproduce this issue on, there's essentially nothing I can do nor have anywhere to start looking from. 

Can someone post their repository + the commit that they tried converting at, and/or the source file(s) that fail?

**Comment by gregjacobs** [comment]
I just bumped the versions of both the `ts-morph` and `typescript` dependencies, which may fix the issue. The max call stack error originally reported is deep within the code of these two dependencies, and may have been optimized already. 

I'm going to close this issue for now, but if anyone can point me to a repository+commit where the utility previously failed so that I can try it again now, that would be greatly appreciated.
