### ISSUE TITLE
[ERROR] Debug Failure. Expected 3 === 1.

### ISSUE THREAD

**Issue by ThatOneCalculator** [gregjacobs/js-to-ts-converter#27]
This error frankly makes no sense. 

[File in question being converted[(https://github.com/Domterion/zer0bin/blob/main/frontend/src/index.js)

Error:
<details>
```
$ npx js-to-ts-converter ./src/
info:   Processing directory: '/home/kainoa/Documents/zer0bin/frontend/src'
info:   Processing the following source files:
info:     /home/kainoa/Documents/zer0bin/frontend/src/index.js
info: 
Converting source files... This may take anywhere from a few minutes to 
tens of minutes or longer depending on how many files are being 
converted.

info:   Adding property declarations to JS Classes...
verbose:        Parsing JS classes in the codebase...
info:   Renaming .js files to .ts
info:   Making parameters optional for calls that supply fewer args than function parameters...
verbose:        Beginning routine to mark function parameters as optional when calls exist that supply fewer args than parameters...
verbose:        Parsing function/method/constructor calls from codebase.
verbose:        Finding all calls to class constructors...
verbose:          Processing classes in source file: /home/kainoa/Documents/zer0bin/frontend/src/index.ts
verbose:        Finding all calls to functions/methods...
verbose:          Processing functions/methods in source file: /home/kainoa/Documents/zer0bin/frontend/src/index.ts
verbose:            Looking for calls to the function: 'postPaste'
verbose:            Looking for calls to the function: 'getPaste'
/home/kainoa/.npm/_npx/adc222a32f8aa038/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:2472
            throw e;
            ^

Error: Debug Failure. Expected 3 === 1. Registered script kind should match new script kind.
    at getOrCreateSourceFileByPath (/home/kainoa/.npm/_npx/adc222a32f8aa038/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:144057:34)
    at Object.getOrCreateSourceFile [as getSourceFile] (/home/kainoa/.npm/_npx/adc222a32f8aa038/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:144015:24)
    at findSourceFile (/home/kainoa/.npm/_npx/adc222a32f8aa038/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:104403:29)
    at /home/kainoa/.npm/_npx/adc222a32f8aa038/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:104280:85
    at getSourceFileFromReferenceWorker (/home/kainoa/.npm/_npx/adc222a32f8aa038/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:104247:34)
    at processSourceFile (/home/kainoa/.npm/_npx/adc222a32f8aa038/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:104280:13)
    at processRootFile (/home/kainoa/.npm/_npx/adc222a32f8aa038/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:104103:13)
    at /home/kainoa/.npm/_npx/adc222a32f8aa038/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:103021:60
    at Object.forEach (/home/kainoa/.npm/_npx/adc222a32f8aa038/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:382:30)
    at Object.createProgram (/home/kainoa/.npm/_npx/adc222a32f8aa038/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:103021:16)
```
</details>

**Comment by gregjacobs** [comment]
Oof, that is definitely not a helpful error.. 

I just updated the version of ts-morph that the project uses. Mind giving it another quick try with the latest version (v0.18.2) and see if you still get that error?

**Comment by gregjacobs** [comment]
I ran the utility against your latest commit before you switched from .js to .ts using TS Migrate. I wasn't aware of that project, and glad that someone else has taken the js->ts conversion reigns since I created this utility about 4 years ago :) 

Anyway, the latest dependencies seem to have solved the issue you reported, but I might be pointing users to TS Migrate at this point instead! Thanks for reporting nonetheless though :)
