### ISSUE TITLE
Converter gets stuck on 'info: 	Renaming .js files to .ts' step

### ISSUE THREAD

**Issue by AntCas** [gregjacobs/js-to-ts-converter#29]
Tried running with npx or by installing globally.

Tried running at the root of a large project and in a directory with only a single .js file.

In both cases the script hangs at the renaming step.

Here's the tail of the output:

```
info: 	
Converting source files... This may take anywhere from a few minutes to 
tens of minutes or longer depending on how many files are being 
converted.

info: 	Adding property declarations to JS Classes...
verbose: 	Parsing JS classes in the codebase...
verbose: 	  Updating class 'MyDocument' in '...../src/pages/_document.js'
verbose: 	    Adding property declarations for properties: ''
info: 	Renaming .js files to .ts
```

No further output after this step. Waiting for several minutes with no indication of progress. No files are changed.

**Comment by gregjacobs** [comment]
Hey @AntCas. Can you point me to your repo so I can try checking it out?

**Comment by robross0606** [comment]
Seeing same problem in my project.  It just sits at the "Renaming .js files to .ts" line

**Comment by robross0606** [comment]
I let it run for a long time and eventually I got this:
```
Manipulation error: Maximum call stack size exceeded

-- Details --
Path: /mnt/c/Code/ncp/study-design-service-clean/src/server.ts
Text: "redacted"
Stack: RangeError: Maximum call stack size exceeded
    at bindParentToChild (/home/bob/.npm/_npx/342/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/dist/typescript.js:20891:69)
    at Object.forEachChildRecursively (/home/bob/.npm/_npx/342/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/dist/typescript.js:30617:27)
    at Object.setParentRecursive (/home/bob/.npm/_npx/342/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/dist/typescript.js:20873:12)
    at fixupParentReferences (/home/bob/.npm/_npx/342/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/dist/typescript.js:31158:16)
    at parseSourceFileWorker (/home/bob/.npm/_npx/342/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/dist/typescript.js:31037:17)
    at Object.parseSourceFile (/home/bob/.npm/_npx/342/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/dist/typescript.js:30855:26)
    at Object.createSourceFile (/home/bob/.npm/_npx/342/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/dist/typescript.js:30653:29)
    at Object.createLanguageServiceSourceFile (/home/bob/.npm/_npx/342/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/dist/typescript.js:161990:29)
    at createCompilerSourceFile (/home/bob/.npm/_npx/342/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/dist/ts-morph-common.js:775:26)
    at DocumentRegistry.updateSourceFile (/home/bob/.npm/_npx/342/lib/node_modules/js-to-ts-converter/node_modules/@ts-morph/common/dist/ts-morph-common.js:2774:31)
```

**Comment by gregjacobs** [comment]
Hey @robross0606, can you provide the URL of your repository so that I can try to reproduce the error?

**Comment by robross0606** [comment]
It is not a public repo

**Comment by gregjacobs** [comment]
Oof, sorry then, without a repository to reproduce the issue and debug, there's basically no way I'm going to be able to track that down. Unless you can create a minimal reproduction in a public repo of the files that cause the issue?

**Comment by robross0606** [comment]
Here's a public repo I just tried and it does the same thing: https://github.com/sheerun/graphqlviz

**Comment by MecBonjourno** [comment]
Hey all, I'm currently getting the same problem. I'm trying to run it in a NextJS project.

**Comment by Shebuka** [comment]
Same issue on this repository https://github.com/the-hideout/tarkov-dev running `npx js-to-ts-converter ./src`

**Comment by stesvis** [comment]
Same here, still happening.

**Comment by kpollock-alphin** [comment]
same here for me. it will work sometimes on small folders

**Comment by davior** [comment]
> same here for me. it will work sometimes on small folders

same-o
